"""Property-based test for `resolveAccess` — CONSISTENT enforcement of authorization (Property 14).

# Feature: multi-user-rag-platform, Property 14: Access authorization is enforced
# consistently — for every relationship between an account and a space (owner |
# shared CHI_DOC | shared GHI | unrelated), `resolveAccess` returns EXACTLY ONE
# expected MucTruyCap for that relationship; and this MucTruyCap has a consistent
# ordering (CHU_SO_HUU >= GHI >= CHI_DOC >= NONE) so a single result gates both read
# operations (>= CHI_DOC) and write operations (>= GHI) at every layer.
# Validates: Requirements 3.2, 3.3, 4.5, 5.2, 6.2, 9.4, 11.7, 18.5, 19.5

The account <-> space relationship is generated by Hypothesis (one of 4 cases).
Each round uses its OWN in-memory SQLite session: it creates the owner TaiKhoan, the
KhongGianTaiLieu, a "subject" TaiKhoan and (depending on the relationship) the
corresponding ChiaSe record, then asserts `resolveAccess(db, chuThe, khongGian)` ==
the expected MucTruyCap. No bcrypt so it's fast → max_examples=200.
"""

from __future__ import annotations

from contextlib import contextmanager

from hypothesis import given, settings
from hypothesis import strategies as st
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

from app.db.database import Base
from app.db.models import ChiaSe, KhongGianTaiLieu, MucQuyen, TaiKhoan
from app.services.share_service import MucTruyCap, resolveAccess


@contextmanager
def _fresh_session():
    """A fresh in-memory SQLite session (schema from Base.metadata) — cleaned up after each round."""
    engine = create_engine("sqlite:///:memory:", future=True)
    Base.metadata.create_all(bind=engine)
    Session = sessionmaker(bind=engine, expire_on_commit=False, future=True)
    db = Session()
    try:
        yield db
    finally:
        db.close()
        engine.dispose()


# The four possible relationships between subject and space → the corresponding expected MucTruyCap.
# "owner": the subject is the owner of the space.
# "share_chi_doc"/"share_ghi": there is a ChiaSe record with the matching mucQuyen.
# "none": not an owner and not shared.
_RELATIONSHIP_TO_ACCESS: dict[str, MucTruyCap] = {
    "owner": MucTruyCap.CHU_SO_HUU,
    "share_ghi": MucTruyCap.GHI,
    "share_chi_doc": MucTruyCap.CHI_DOC,
    "none": MucTruyCap.NONE,
}


@settings(max_examples=40, deadline=None)
@given(quanHe=st.sampled_from(sorted(_RELATIONSHIP_TO_ACCESS)))
def test_uy_quyen_thuc_thi_nhat_quan(quanHe):
    mucMongDoi = _RELATIONSHIP_TO_ACCESS[quanHe]

    with _fresh_session() as db:
        chuSoHuu = TaiKhoan(email="chu@x.com", tenDangNhap="chu", matKhauHash="h")
        db.add(chuSoHuu)
        db.commit()

        khongGian = KhongGianTaiLieu(
            ten="KG",
            chuSoHuuId=chuSoHuu.id,
            embeddingProvider="e5",
            collectionName="ws_x",
        )
        db.add(khongGian)
        db.commit()

        # The subject being authorized: either the owner itself (owner) or another account.
        if quanHe == "owner":
            chuThe = chuSoHuu
        else:
            chuThe = TaiKhoan(email="khach@x.com", tenDangNhap="khach", matKhauHash="h")
            db.add(chuThe)
            db.commit()

        if quanHe == "share_chi_doc":
            db.add(ChiaSe(khongGianId=khongGian.id, taiKhoanId=chuThe.id, mucQuyen=MucQuyen.CHI_DOC))
            db.commit()
        elif quanHe == "share_ghi":
            db.add(ChiaSe(khongGianId=khongGian.id, taiKhoanId=chuThe.id, mucQuyen=MucQuyen.GHI))
            db.commit()

        muc = resolveAccess(db, chuThe, khongGian)

        # (1) Returns EXACTLY ONE expected MucTruyCap for the relationship (R3.2, R3.3, R11.7, ...).
        assert muc == mucMongDoi

        # (2) Ordering invariant: a single result gates read/write consistently.
        #     read needs >= CHI_DOC; write needs >= GHI; the ordering must agree with the relationship.
        choPhepDoc = muc >= MucTruyCap.CHI_DOC
        choPhepGhi = muc >= MucTruyCap.GHI
        # Having write permission guarantees read permission (ordering is not contradictory).
        assert not choPhepGhi or choPhepDoc
        # Map relationship -> expected read/write capability (consistent gating at every layer).
        assert choPhepDoc == (quanHe in {"owner", "share_ghi", "share_chi_doc"})
        assert choPhepGhi == (quanHe in {"owner", "share_ghi"})
