"""Property-based test for the Chunk preview after upload (Property 21, task 8.3).

# Feature: multi-user-rag-platform, Property 21: Ban xem truoc phan anh day du
# Chunk theo thu tu — voi van ban tai lieu bat ky (khong rong sau strip),
# `DocumentPipeline.uploadDocument` tra ve `PreviewResult{soChunk, chunks}` sao cho:
#   (a) len(chunks) == soChunk (so luong khop);
#   (b) thuTu cua chunks la 0,1,2,...,N-1 lien tuc va dung thu tu;
#   (c) moi chunk co noiDung khong rong (sau strip);
#   (d) preview khop dung cac ban ghi Chunk da luu trong RDB (cung so luong, cung
#       thu tu, cung noiDung, cung ranh gioi).
# Validates: Requirements 18.1

Upload does not embed (R5.13/5.14), so there is NO need to fake Embedding_Provider /
Vector_Store: `DocumentPipeline(db)` is enough (the default VectorStore is import-safe, lazy,
and not touched during upload). Each example uses a FRESH in-memory SQLite; the account + space
are created directly. The text generated by Hypothesis mixes several fragments (lowercase words,
markdown headings, "Dieu N." lines, form-feed page breaks, unicode) + free text; whitespace-only
text is filtered out with `assume` (empty text -> 0 chunks -> rejected, outside the scope of this
property). max_examples=150.
"""

from __future__ import annotations

import pytest
from hypothesis import HealthCheck, assume, example, given, settings
from hypothesis import strategies as st
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

from app.chunking.registry import discover_chunkers
from app.db.database import Base
from app.db.models import (
    Chunk,
    HanMuc,
    KhongGianTaiLieu,
    TaiKhoan,
    TaiLieu,
    TrangThaiTaiLieu,
)
from app.pipelines.document_pipeline import DocumentPipeline


# --- Load the chunker registry once ----------------------------------------
@pytest.fixture(scope="module", autouse=True)
def _nap_chunker():
    discover_chunkers()


# --- Generate varied text (like Property 22, ensuring a multi-chunk branch) --
_MANH = st.sampled_from(
    [
        "noi dung",
        "phan tich tinh huong phap ly",
        "café résumé",
        "日本語のテキスト",
        "khoan 1 muc a",
        " ",
        "\t",
        "\n",
        "\n\n",
        "\f",
        "# Tieu de chinh",
        "## Muc con",
        "Điều 1.",
        "Điều 23:",
        "Quy dinh chung ve doi tuong ap dung trong van ban nay.",
    ]
)


@st.composite
def _van_ban_da_dang(draw) -> str:
    so_manh = draw(st.integers(min_value=1, max_value=14))
    return "".join(draw(_MANH) for _ in range(so_manh))


_van_ban_strategy = st.one_of(_van_ban_da_dang(), st.text(min_size=1, max_size=300))


# --- Utility: FRESH in-memory SQLite + account + space ---------------------
def _tao_session():
    engine = create_engine("sqlite:///:memory:", future=True)
    Base.metadata.create_all(bind=engine)
    Session = sessionmaker(bind=engine, expire_on_commit=False, future=True)
    return engine, Session()


def _tao_tai_khoan_va_khong_gian(db) -> tuple[TaiKhoan, KhongGianTaiLieu]:
    tk = TaiKhoan(email="chu@x.com", tenDangNhap="chu", matKhauHash="h")
    tk.hanMuc = HanMuc()
    db.add(tk)
    db.commit()
    kg = KhongGianTaiLieu(
        ten="KG",
        moTa="",
        chuSoHuuId=tk.id,
        embeddingProvider="huggingface",
        collectionName="ws_tmp",
    )
    db.add(kg)
    db.flush()
    kg.collectionName = f"ws_{kg.id}"
    db.commit()
    return tk, kg


def _kiem_preview(text: str) -> None:
    """Upload `text` into a fresh SQLite and check the 4 invariants of Property 21."""
    engine, db = _tao_session()
    try:
        chu, kg = _tao_tai_khoan_va_khong_gian(db)
        pipeline = DocumentPipeline(db)

        ketQua = pipeline.uploadDocument(
            chu, kg, text.encode("utf-8"), "a.txt", "txt"
        )

        # (a) the count matches soChunk.
        n = ketQua.soChunk
        assert n >= 1, f"van ban khong rong nhung soChunk={n}: {text!r}"
        assert len(ketQua.chunks) == n, (
            f"len(chunks)={len(ketQua.chunks)} != soChunk={n}: {text!r}"
        )

        # (b) thuTu = 0,1,2,...,N-1 contiguous and in order.
        assert [c.thuTu for c in ketQua.chunks] == list(range(n)), (
            f"thuTu khong lien tuc/dung thu tu: "
            f"{[c.thuTu for c in ketQua.chunks]} (text={text!r})"
        )

        # (c) every noiDung is non-empty (after strip).
        for c in ketQua.chunks:
            assert c.noiDung.strip(), f"chunk thuTu={c.thuTu} co noiDung rong: {text!r}"

        # (d) matches the Chunk records saved in the RDB.
        taiLieu = db.query(TaiLieu).one()
        assert taiLieu.trangThai == TrangThaiTaiLieu.DA_PARSE_CHO_DUYET
        assert taiLieu.soChunk == n
        chunkDb = (
            db.query(Chunk)
            .filter(Chunk.taiLieuId == taiLieu.id)
            .order_by(Chunk.thuTu)
            .all()
        )
        assert len(chunkDb) == n, f"so Chunk RDB={len(chunkDb)} != {n}: {text!r}"
        for cPreview, cDb in zip(ketQua.chunks, chunkDb):
            assert cPreview.id == cDb.id
            assert cPreview.thuTu == cDb.thuTu
            assert cPreview.viTriBatDau == cDb.viTriBatDau
            assert cPreview.viTriKetThuc == cDb.viTriKetThuc
            assert cPreview.noiDung == cDb.noiDung
    finally:
        db.close()
        engine.dispose()


@settings(
    max_examples=150,
    deadline=None,
    suppress_health_check=[HealthCheck.function_scoped_fixture],
)
@given(text=_van_ban_strategy)
# Anchor examples: text with multiple Dieu (vietnamese-law), markdown, page breaks -> multiple chunks.
@example(text="Điều 1. Pham vi dieu chinh.\nĐiều 2: Giai thich tu ngu.")
@example(text="# Heading\nNoi dung.\n\n## Muc\nChi tiet.")
@example(text="Trang mot.\fTrang hai.\fTrang ba.")
@example(text="noi dung")
def test_ban_xem_truoc_phan_anh_day_du_chunk(text):
    assume(text.strip())  # whitespace-only text -> 0 chunks, out of scope.
    _kiem_preview(text)
