"""Property-based test for Property 24 (task 8.7): a failed re-chunk keeps the old Chunks intact.

# Feature: multi-user-rag-platform, Property 24: A failed re-chunk / re-embed keeps
# the old Chunks intact — for any uploaded document, if `DocumentPipeline.rechunk`
# fails (for one of the two causes Hypothesis picks:
#   (1) a non-existent strategy name -> ValidationError BEFORE writing to the DB; or
#   (2) an error while committing the replace-set transaction (injected error: monkeypatch db.commit to raise once))
# then rechunk MUST raise, and AFTERWARDS the Chunk records (count, order, id,
# noiDung, boundaries) as well as `taiLieu.trangThai` MUST stay exactly as they were
# before the failed re-chunk (comparing a fingerprint before/after).
# Validates: Requirements 5.6, 18.10

REUSE fakes (FakeEmbeddingProvider / FakeClient / FakeCollection) from
`test_document_pipeline_rechunk` as required. Each example uses a NEW in-memory
SQLite. Text is generated by Hypothesis (mixing several fragments + free text),
filtering out whitespace-only text with `assume`. max_examples=100.
"""

from __future__ import annotations

import pytest
from hypothesis import HealthCheck, assume, example, given, settings
from hypothesis import strategies as st
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

from app.chunking.registry import discover_chunkers
from app.db.database import Base
from app.db.models import (
    Chunk,
    HanMuc,
    KhongGianTaiLieu,
    TaiKhoan,
    TaiLieu,
    TrangThaiTaiLieu,
)
from app.pipelines.document_pipeline import DocumentPipeline
from app.storage.vector_store import VectorStore

# REUSE the fakes validated in the task 8.5 unit test.
from test_document_pipeline_rechunk import FakeClient, FakeEmbeddingProvider


# --- Load the chunker registry once ----------------------------------------
@pytest.fixture(scope="module", autouse=True)
def _nap_chunker():
    discover_chunkers()


# --- Generate varied text (produces several different chunks) ---------------
_MANH = st.sampled_from(
    [
        "noi dung",
        "phan tich tinh huong phap ly",
        "café résumé",
        "日本語のテキスト",
        "khoan 1 muc a",
        " ",
        "\t",
        "\n",
        "\n\n",
        "\f",
        "# Tieu de chinh",
        "## Muc con",
        "Điều 1.",
        "Điều 23:",
        "Quy dinh chung ve doi tuong ap dung trong van ban nay.",
    ]
)


@st.composite
def _van_ban_da_dang(draw) -> str:
    so_manh = draw(st.integers(min_value=1, max_value=14))
    return "".join(draw(_MANH) for _ in range(so_manh))


_van_ban_strategy = st.one_of(_van_ban_da_dang(), st.text(min_size=1, max_size=300))


# --- Utility: NEW in-memory SQLite + account + workspace + pipeline ---------
def _tao_session():
    engine = create_engine("sqlite:///:memory:", future=True)
    Base.metadata.create_all(bind=engine)
    Session = sessionmaker(bind=engine, expire_on_commit=False, future=True)
    return engine, Session()


def _tao_tai_khoan_va_khong_gian(db) -> tuple[TaiKhoan, KhongGianTaiLieu]:
    tk = TaiKhoan(email="chu@x.com", tenDangNhap="chu", matKhauHash="h")
    tk.hanMuc = HanMuc()
    db.add(tk)
    db.commit()
    kg = KhongGianTaiLieu(
        ten="KG",
        moTa="",
        chuSoHuuId=tk.id,
        embeddingProvider="huggingface",
        collectionName="ws_tmp",
    )
    db.add(kg)
    db.flush()
    kg.collectionName = f"ws_{kg.id}"
    db.commit()
    return tk, kg


def _fingerprint(db, taiLieuId: str):
    """Fingerprint of the Chunks (id, thuTu, batDau, ketThuc, noiDung) ordered by thuTu."""
    chunks = (
        db.query(Chunk)
        .filter(Chunk.taiLieuId == taiLieuId)
        .order_by(Chunk.thuTu)
        .all()
    )
    return [
        (c.id, c.thuTu, c.viTriBatDau, c.viTriKetThuc, c.noiDung) for c in chunks
    ]


def _kiem_cat_lai_that_bai_giu_nguyen(text: str, daEmbed: bool, loiCommit: bool) -> None:
    """Upload `text`, (optionally) embed, then re-chunk with an error trigger; check it is unchanged."""
    engine, db = _tao_session()
    try:
        chu, kg = _tao_tai_khoan_va_khong_gian(db)
        pipeline = DocumentPipeline(
            db,
            vectorStore=VectorStore(client=FakeClient()),
            embeddingProvider=FakeEmbeddingProvider(),
        )

        pipeline.uploadDocument(chu, kg, text.encode("utf-8"), "a.txt", "txt")
        taiLieu = db.query(TaiLieu).one()
        taiLieuId = taiLieu.id

        if daEmbed:
            pipeline.commitEmbedding(chu, taiLieuId)
            db.refresh(taiLieu)

        # DB state before the failed re-chunk.
        fpTruoc = _fingerprint(db, taiLieuId)
        trangThaiTruoc = taiLieu.trangThai
        assert len(fpTruoc) >= 1

        if loiCommit:
            # (2) Inject an error mid replace-set transaction: db.commit raises exactly once.
            commitGoc = db.commit
            daNo = {"x": False}

            def commitNo():
                if not daNo["x"]:
                    daNo["x"] = True
                    raise RuntimeError("loi commit bom vao (test Property 24)")
                return commitGoc()

            db.commit = commitNo  # type: ignore[method-assign]
            try:
                with pytest.raises(Exception):  # noqa: B017 — RuntimeError from injected commit
                    pipeline.rechunk(chu, taiLieuId)
            finally:
                db.commit = commitGoc  # type: ignore[method-assign]
        else:
            # (1) A non-existent strategy name -> ValidationError BEFORE writing to the DB.
            from app.errors import ValidationError

            with pytest.raises(ValidationError):
                pipeline.rechunk(
                    chu, taiLieuId, chienLuocChunk="chien-luoc-khong-ton-tai-xyz"
                )

        # After the failure: the old Chunks stay intact (count, order, id, noiDung,
        # boundaries) and the document status is unchanged (R5.6, R18.10).
        db.expire_all()
        taiLieu = db.get(TaiLieu, taiLieuId)
        fpSau = _fingerprint(db, taiLieuId)
        assert fpSau == fpTruoc, (
            f"Chunk cu bi thay doi sau khi cat lai that bai\n"
            f"truoc={fpTruoc}\nsau  ={fpSau}\n(text={text!r}, daEmbed={daEmbed}, "
            f"loiCommit={loiCommit})"
        )
        assert taiLieu.trangThai == trangThaiTruoc, (
            f"trangThai doi: {trangThaiTruoc} -> {taiLieu.trangThai}"
        )
        assert taiLieu.soChunk == len(fpTruoc)
    finally:
        db.close()
        engine.dispose()


@settings(
    max_examples=100,
    deadline=None,
    suppress_health_check=[HealthCheck.function_scoped_fixture],
)
@given(
    text=_van_ban_strategy,
    daEmbed=st.booleans(),
    loiCommit=st.booleans(),
)
# Pinned examples: both failure causes, both states (awaiting review / embedded).
@example(text="Điều 1. Pham vi.\nĐiều 2: Giai thich.", daEmbed=False, loiCommit=False)
@example(text="Điều 1. Pham vi.\nĐiều 2: Giai thich.", daEmbed=True, loiCommit=True)
@example(text="noi dung", daEmbed=True, loiCommit=False)
@example(text="# Heading\nNoi dung.\n\n## Muc\nChi tiet.", daEmbed=False, loiCommit=True)
def test_cat_lai_that_bai_giu_nguyen_chunk_cu(text, daEmbed, loiCommit):
    assume(text.strip())  # whitespace-only text -> 0 chunks on upload, out of scope.
    _kiem_cat_lai_that_bai_giu_nguyen(text, daEmbed, loiCommit)
