"""Property-based test for the share-permission matrix (Property 43).

# Feature: multi-user-rag-platform, Property 43: Share-permission matrix — for every
# valid share mucQuyen (CHI_DOC | GHI) granted to a NON-owner account, the effective
# access level (resolveAccess) and the derived capability matrix must match the
# granted permission: CHI_DOC allows read/query but NOT write (upload/delete/edit) ->
# 403 (R11.2); GHI allows read + write (upload/delete/edit/change retrieval config)
# (R11.3); and owner-only operations (sharing / renaming / deleting the workspace)
# are NEVER allowed for a shared account (they require CHU_SO_HUU).
# Validates: Requirements 11.2, 11.3

Each round uses ONE separate in-memory SQLite session (schema from Base.metadata):
create owner + workspace + a target account, call `ShareService.grantShare(...,
mucQuyen)` with a mucQuyen generated by Hypothesis, then assert the resulting
MucTruyCap and the capability matrix (read/write/owner) derived from it. Accounts are
created directly (no bcrypt) so it is fast → max_examples=200.
"""

from __future__ import annotations

from contextlib import contextmanager

from hypothesis import given, settings
from hypothesis import strategies as st
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

from app.db.database import Base
from app.db.models import KhongGianTaiLieu, MucQuyen, TaiKhoan
from app.services.share_service import MucTruyCap, ShareService


@contextmanager
def _fresh_session():
    """A fresh in-memory SQLite session for each round — cleaned up after use."""
    engine = create_engine("sqlite:///:memory:", future=True)
    Base.metadata.create_all(bind=engine)
    Session = sessionmaker(bind=engine, expire_on_commit=False, future=True)
    db = Session()
    try:
        yield db
    finally:
        db.close()
        engine.dispose()


# Map share mucQuyen -> expected effective access level of the target account.
_MUC_QUYEN_SANG_TRUY_CAP = {
    MucQuyen.CHI_DOC: MucTruyCap.CHI_DOC,
    MucQuyen.GHI: MucTruyCap.GHI,
}


@settings(max_examples=40, deadline=None)
@given(mucQuyen=st.sampled_from([MucQuyen.CHI_DOC, MucQuyen.GHI]))
def test_ma_tran_quyen_chia_se(mucQuyen):
    with _fresh_session() as db:
        service = ShareService(db)

        chuSoHuu = TaiKhoan(email="chu@x.com", tenDangNhap="chu", matKhauHash="h")
        khach = TaiKhoan(email="khach@x.com", tenDangNhap="khach", matKhauHash="h")
        db.add_all([chuSoHuu, khach])
        db.commit()

        khongGian = KhongGianTaiLieu(
            ten="KG",
            chuSoHuuId=chuSoHuu.id,
            embeddingProvider="e5",
            collectionName="ws_x",
        )
        db.add(khongGian)
        db.commit()

        service.grantShare(chuSoHuu, khongGian.id, khach.id, mucQuyen)

        # (1) The target account's effective access level matches the granted mucQuyen.
        muc = service.resolveAccess(khach, khongGian)
        assert muc == _MUC_QUYEN_SANG_TRUY_CAP[mucQuyen]

        # (2) Capability matrix derived from the access level (consistent gating across
        #     all layers): read/query needs >= CHI_DOC; write (upload/delete/edit) needs
        #     >= GHI; owner-only operations (share/rename/delete workspace) need CHU_SO_HUU.
        choPhepDoc = muc >= MucTruyCap.CHI_DOC
        choPhepGhi = muc >= MucTruyCap.GHI
        choPhepChuSoHuu = muc >= MucTruyCap.CHU_SO_HUU

        # CHI_DOC: can read, can NOT write (R11.2). GHI: read + write (R11.3).
        assert choPhepDoc is True
        assert choPhepGhi == (mucQuyen == MucQuyen.GHI)
        # A shared account is never the owner → NO owner-only operations
        # (share / rename / delete workspace), even at the GHI level.
        assert choPhepChuSoHuu is False

        # (3) Ordering invariant: write implies read; owner implies write.
        assert not choPhepGhi or choPhepDoc
        assert not choPhepChuSoHuu or choPhepGhi
