"""Property-based test for basic chunk invariants (Property 22).

# Feature: multi-user-rag-platform, Property 22: Every non-empty text produces at
# least one Chunk — for any `text` and EVERY ChienLuocChunk registered in the registry
# (recursive, structure-aware, page, semantic, vietnamese-law, and any new strategy
# added later): if `text` is non-empty after strip then `chunk()` produces >= 1
# ChunkData, each ChunkData has a non-empty `noiDung` AND positions that correctly
# reference the original text (text[viTriBatDau:viTriKetThuc] == noiDung). If `text` is
# empty or whitespace-only then `chunk()` returns an empty list (0 chunks).
# Validates: Requirements 15.1, 15.2

Walks the ENTIRE `CHUNKER_REGISTRY` (via `discover_chunkers()` + `get_chunker`) so every
newly added strategy is automatically checked. Text generated by Hypothesis mixes many
fragments: lowercase words, newlines, markdown headings, "Điều N." lines, form-feed page
breaks, unicode characters — producing text that may have content OR be whitespace-only
(covering both branches). The "non-empty" oracle uses `str.strip()` — matching exactly
each strategy's guard. max_examples=200.
"""

from __future__ import annotations

from hypothesis import example, given, settings
from hypothesis import strategies as st

from app.chunking import registry as chunk_reg
from app.chunking.base import ChunkData, ChunkParams

# Load the registry once: get EVERY registered strategy (including ones added later).
chunk_reg.discover_chunkers()
TEN_CHIEN_LUOC = sorted(chunk_reg.CHUNKER_REGISTRY)

# Small parameters so even the sample text can be split into multiple segments in the test.
THAM_SO = ChunkParams(kichThuocMucTieu=80, doChongLan=15)

# Varied text fragments: words/phrases (including unicode), whitespace, markdown headings,
# "Điều N." lines, form-feed page breaks.
_MANH = st.sampled_from(
    [
        "noi dung",
        "phan tich tinh huong phap ly",
        "café résumé",
        "日本語のテキスト",
        "khoan 1 muc a",
        " ",
        "\t",
        "\n",
        "\n\n",
        "\f",
        "# Tieu de chinh",
        "## Muc con",
        "Điều 1.",
        "Điều 23:",
        "Điều 5",  # no ./: after the number → not an Article boundary
        "Quy dinh chung ve doi tuong ap dung trong van ban nay.",
    ]
)


@st.composite
def _van_ban_da_dang(draw) -> str:
    """Concatenate several fragments into varied text (may yield content or whitespace only)."""
    so_manh = draw(st.integers(min_value=0, max_value=12))
    return "".join(draw(_MANH) for _ in range(so_manh))


# Mix the structured concatenated text with completely free unicode text (stronger fuzzing).
_van_ban_strategy = st.one_of(
    _van_ban_da_dang(),
    st.text(max_size=300),
)


def _kiem_bat_bien_mot_chien_luoc(ten: str, text: str) -> None:
    """Check the Property 22 invariant for ONE strategy on `text`."""
    chunker = chunk_reg.get_chunker(ten)()
    chunks = chunker.chunk(text, THAM_SO)

    if text.strip():
        # Non-empty text → >= 1 chunk, each chunk has non-empty noiDung + correct positions.
        assert len(chunks) >= 1, f"[{ten}] van ban khong rong nhung 0 chunk: {text!r}"
        for c in chunks:
            assert isinstance(c, ChunkData)
            assert c.noiDung.strip(), f"[{ten}] noiDung rong (R15.2): {text!r}"
            assert (
                text[c.viTriBatDau:c.viTriKetThuc] == c.noiDung
            ), f"[{ten}] vi tri khong khop van ban goc: {text!r}"
    else:
        # Empty / whitespace-only text → 0 chunks.
        assert chunks == [], f"[{ten}] van ban rong nhung co chunk: {text!r}"


@settings(max_examples=40, deadline=None)
@given(text=_van_ban_strategy)
# Anchor examples: empty / whitespace-only → 0 chunks; with content → >= 1 chunk.
@example(text="")
@example(text="   \t\n\f  ")
@example(text="Điều 1. Pham vi dieu chinh.\nĐiều 2: Giai thich tu ngu.")
@example(text="# Heading\nNoi dung.\n\n## Muc\nChi tiet.")
@example(text="Trang mot.\fTrang hai.\fTrang ba.")
def test_moi_van_ban_khong_rong_tao_it_nhat_mot_chunk(text):
    # Walk EVERY registered strategy → new strategies are covered automatically.
    for ten in TEN_CHIEN_LUOC:
        _kiem_bat_bien_mot_chien_luoc(ten, text)
