"""Property-based test for workspace name/description validation (Property 18).

# Feature: multi-user-rag-platform, Property 18: Workspace name and description
# validation — for any `ten`/`moTa` (possibly with leading/trailing whitespace),
# `createWorkspace` SUCCEEDS if and only if the trimmed length of `ten` is in
# [1, 100] AND the trimmed length of `moTa` is <= 1000. On success, `ten`/`moTa` are
# stored in the DB as exactly the trimmed values. Otherwise → `ValidationError` and
# NO KhongGianTaiLieu record is created.
# Validates: Requirements 4.1, 4.2, 4.3, 4.4

`ten`/`moTa` are generated by Hypothesis: the core part (no leading/trailing
whitespace) with length varying around the boundaries (0/1/100/101 for ten;
0/1000/1001 for moTa) plus optional whitespace padding on both ends to exercise trim
behavior. Each round uses ONE separate in-memory SQLite session: the owner TaiKhoan
is created directly (fake matKhauHash, no bcrypt) with a generous HanMuc limit → the
quota never blocks. The length oracle uses `str.strip()` to match pydantic
(confirmed: pydantic v2 trims BEFORE checking min/max_length). max_examples=200.
"""

from __future__ import annotations

from contextlib import contextmanager

from hypothesis import given, settings
from hypothesis import strategies as st
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

from app.db.database import Base
from app.db.models import HanMuc, KhongGianTaiLieu, TaiKhoan
from app.errors import ValidationError
from app.services.workspace_service import WorkspaceService


@contextmanager
def _fresh_session():
    """Fresh in-memory SQLite session (schema from Base.metadata) — cleaned up after each round."""
    engine = create_engine("sqlite:///:memory:", future=True)
    Base.metadata.create_all(bind=engine)
    Session = sessionmaker(bind=engine, expire_on_commit=False, future=True)
    db = Session()
    try:
        yield db
    finally:
        db.close()
        engine.dispose()


def _tao_chu_so_huu(db) -> TaiKhoan:
    """Create the owner directly with a fake matKhauHash + a generous HanMuc (never blocks)."""
    tk = TaiKhoan(email="chu@x.com", tenDangNhap="chu", matKhauHash="h")
    tk.hanMuc = HanMuc(soKhongGianToiDa=10_000)
    db.add(tk)
    db.commit()
    return tk


# The "core" part (no leading/trailing whitespace). Sampled around the valid
# boundaries to cover both branches (valid / invalid) within 200 rounds.
def _khoang_trang() -> st.SearchStrategy[str]:
    return st.text(alphabet=" \t\n", max_size=3)


@st.composite
def _chuoi_kem_khoang_trang(draw, do_dai_loi: st.SearchStrategy[int]):
    """Generate a string = whitespace + core + whitespace, where `core` has no
    whitespace at either end (so the length after trim equals the length of `core`)."""
    n = draw(do_dai_loi)
    # The "core" characters are NOT whitespace, so strip doesn't eat into the core.
    loi = draw(
        st.text(
            alphabet=st.characters(blacklist_categories=("Cc", "Cs", "Zs", "Zl", "Zp")),
            min_size=n,
            max_size=n,
        )
    )
    return draw(_khoang_trang()) + loi + draw(_khoang_trang())


_ten_strategy = _chuoi_kem_khoang_trang(st.integers(min_value=0, max_value=102))
_mota_strategy = st.one_of(
    _chuoi_kem_khoang_trang(st.integers(min_value=0, max_value=5)),
    _chuoi_kem_khoang_trang(st.integers(min_value=998, max_value=1002)),
)


@settings(max_examples=40, deadline=None)
@given(ten=_ten_strategy, moTa=_mota_strategy)
def test_hop_le_hoa_ten_mo_ta_khong_gian(ten, moTa):
    tenTrim = ten.strip()
    moTaTrim = moTa.strip()
    hopLeMongDoi = (1 <= len(tenTrim) <= 100) and (len(moTaTrim) <= 1000)

    with _fresh_session() as db:
        chu = _tao_chu_so_huu(db)
        service = WorkspaceService(db)

        if hopLeMongDoi:
            kg = service.createWorkspace(chu, ten, moTa)
            # Stored in the DB as exactly the trimmed values (R4.1, R4.4).
            assert kg.ten == tenTrim
            assert kg.moTa == moTaTrim
            luu = db.get(KhongGianTaiLieu, kg.id)
            assert luu is not None
            assert luu.ten == tenTrim
            assert luu.moTa == moTaTrim
            assert db.query(KhongGianTaiLieu).count() == 1
        else:
            try:
                service.createWorkspace(chu, ten, moTa)
                raised = False
            except ValidationError:
                raised = True
            assert raised, f"Mong doi ValidationError cho ten={ten!r}, moTa={moTa!r}"
            # No record is created when invalid (R4.2).
            assert db.query(KhongGianTaiLieu).count() == 0
